In [3]:
with open('test.yw') as f:
    li = f.readlines()

In [4]:
li

['#@begin Linear_OR #@desc Linear OpenRefine Workflow\n',
 '#@param col-name:Twitter\n',
 '#@param col-name:street\n',
 '#@param col-name:y\n',
 '#@param expression:value.trim()\n',
 '#@param col-name:Season3_Start_Date\n',
 '#@param col-name:Season1_End_Date\n',
 '#@param col-name:Season2_End_Date\n',
 '#@param col-name:Website\n',
 '#@param col-name:x\n',
 '#@param col-name:Season1_Start_Date\n',
 '#@param col-name:Facebook\n',
 '#@param col-name:zip\n',
 '#@param col-name:MarketName\n',
 '#@param col-name:Season2_Start_Date\n',
 '#@param col-name:Youtube\n',
 '#@param col-name:updateTime\n',
 '#@param col-name:County\n',
 '#@param expression:value.toTitlecase()\n',
 '#@param col-name:city\n',
 '#@param expression:value.toDate()\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@param col-name:Season4_End_Date\n',
 '#@param col-name:Column\n',
 '#@param col-name:Season4_Start_Date\n',
 '#@param col-name:Season3_End_Date\n',
 '#@param col-name:State\n',
 '#@param expression:value.toNumber()\n',
 '#@in table0\n',
 '#@out table55\n',
 '#@begin core/mass-edit0#@desc Mass edit cells in column MarketName\n',
 '#@param col-name:MarketName\n',
 '#@in table0\n',
 '#@out table1\n',
 '#@end core/mass-edit0\n',
 '#@begin core/text-transform0#@desc Text transform on cells in column MarketName using expression value.toTitlecase()\n',
 '#@param col-name:MarketName\n',
 '#@param expression:value.toTitlecase()\n',
 '#@in table1\n',
 '#@out table2\n',
 '#@end core/text-transform0\n',
 '#@begin core/text-transform1#@desc Text transform on cells in column MarketName using expression value.trim()\n',
 '#@param col-name:MarketName\n',
 '#@param expression:value.trim()\n',
 '#@in table2\n',
 '#@out table3\n',
 '#@end core/text-transform1\n',
 '#@begin core/text-transform2#@desc Text transform on cells in column street using expression value.trim()\n',
 '#@param col-name:street\n',
 '#@param expression:value.trim()\n',
 '#@in table3\n',
 '#@out table4\n',
 '#@end core/text-transform2\n',
 '#@begin core/text-transform3#@desc Text transform on cells in column street using expression value.trim()\n',
 '#@param col-name:street\n',
 '#@param expression:value.trim()\n',
 '#@in table4\n',
 '#@out table5\n',
 '#@end core/text-transform3\n',
 '#@begin core/text-transform4#@desc Text transform on cells in column city using expression value.trim()\n',
 '#@param col-name:city\n',
 '#@param expression:value.trim()\n',
 '#@in table5\n',
 '#@out table6\n',
 '#@end core/text-transform4\n',
 '#@begin core/text-transform5#@desc Text transform on cells in column city using expression value.toTitlecase()\n',
 '#@param col-name:city\n',
 '#@param expression:value.toTitlecase()\n',
 '#@in table6\n',
 '#@out table7\n',
 '#@end core/text-transform5\n',
 '#@begin core/text-transform6#@desc Text transform on cells in column County using expression value.trim()\n',
 '#@param col-name:County\n',
 '#@param expression:value.trim()\n',
 '#@in table7\n',
 '#@out table8\n',
 '#@end core/text-transform6\n',
 '#@begin core/text-transform7#@desc Text transform on cells in column County using expression value.toTitlecase()\n',
 '#@param col-name:County\n',
 '#@param expression:value.toTitlecase()\n',
 '#@in table8\n',
 '#@out table9\n',
 '#@end core/text-transform7\n',
 '#@begin core/text-transform8#@desc Text transform on cells in column State using expression value.trim()\n',
 '#@param col-name:State\n',
 '#@param expression:value.trim()\n',
 '#@in table9\n',
 '#@out table10\n',
 '#@end core/text-transform8\n',
 '#@begin core/text-transform9#@desc Text transform on cells in column State using expression value.toTitlecase()\n',
 '#@param col-name:State\n',
 '#@param expression:value.toTitlecase()\n',
 '#@in table10\n',
 '#@out table11\n',
 '#@end core/text-transform9\n',
 '#@begin core/text-transform10#@desc Text transform on cells in column Website using expression value.trim()\n',
 '#@param col-name:Website\n',
 '#@param expression:value.trim()\n',
 '#@in table11\n',
 '#@out table12\n',
 '#@end core/text-transform10\n',
 '#@begin core/text-transform11#@desc Text transform on cells in column Facebook using expression value.trim()\n',
 '#@param col-name:Facebook\n',
 '#@param expression:value.trim()\n',
 '#@in table12\n',
 '#@out table13\n',
 '#@end core/text-transform11\n',
 '#@begin core/text-transform12#@desc Text transform on cells in column Twitter using expression value.trim()\n',
 '#@param col-name:Twitter\n',
 '#@param expression:value.trim()\n',
 '#@in table13\n',
 '#@out table14\n',
 '#@end core/text-transform12\n',
 '#@begin core/text-transform13#@desc Text transform on cells in column Youtube using expression value.trim()\n',
 '#@param col-name:Youtube\n',
 '#@param expression:value.trim()\n',
 '#@in table14\n',
 '#@out table15\n',
 '#@end core/text-transform13\n',
 '#@begin core/text-transform14#@desc Text transform on cells in column zip using expression value.toNumber()\n',
 '#@param col-name:zip\n',
 '#@param expression:value.toNumber()\n',
 '#@in table15\n',
 '#@out table16\n',
 '#@end core/text-transform14\n',
 '#@begin core/text-transform15#@desc Text transform on cells in column x using expression value.toNumber()\n',
 '#@param col-name:x\n',
 '#@param expression:value.toNumber()\n',
 '#@in table16\n',
 '#@out table17\n',
 '#@end core/text-transform15\n',
 '#@begin core/text-transform16#@desc Text transform on cells in column y using expression value.toNumber()\n',
 '#@param col-name:y\n',
 '#@param expression:value.toNumber()\n',
 '#@in table17\n',
 '#@out table18\n',
 '#@end core/text-transform16\n',
 '#@begin core/text-transform17#@desc Text transform on cells in column updateTime using expression value.toDate()\n',
 '#@param col-name:updateTime\n',
 '#@param expression:value.toDate()\n',
 '#@in table18\n',
 '#@out table19\n',
 '#@end core/text-transform17\n',
 '#@begin core/text-transform18#@desc Text transform on cells in column Season1 Start Date using expression value.toDate()\n',
 '#@param col-name:Season1_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table19\n',
 '#@out table20\n',
 '#@end core/text-transform18\n',
 '#@begin core/text-transform19#@desc Text transform on cells in column Season1 End Date using expression value.toDate()\n',
 '#@param col-name:Season1_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table20\n',
 '#@out table21\n',
 '#@end core/text-transform19\n',
 '#@begin core/text-transform20#@desc Text transform on cells in column Season2 Start Date using expression value.toDate()\n',
 '#@param col-name:Season2_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table21\n',
 '#@out table22\n',
 '#@end core/text-transform20\n',
 '#@begin core/text-transform21#@desc Text transform on cells in column Season2 End Date using expression value.toDate()\n',
 '#@param col-name:Season2_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table22\n',
 '#@out table23\n',
 '#@end core/text-transform21\n',
 '#@begin core/text-transform22#@desc Text transform on cells in column Season3 Start Date using expression value.toDate()\n',
 '#@param col-name:Season3_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table23\n',
 '#@out table24\n',
 '#@end core/text-transform22\n',
 '#@begin core/text-transform23#@desc Text transform on cells in column Season3 End Date using expression value.toDate()\n',
 '#@param col-name:Season3_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table24\n',
 '#@out table25\n',
 '#@end core/text-transform23\n',
 '#@begin core/text-transform24#@desc Text transform on cells in column Season4 Start Date using expression value.toDate()\n',
 '#@param col-name:Season4_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table25\n',
 '#@out table26\n',
 '#@end core/text-transform24\n',
 '#@begin core/text-transform25#@desc Text transform on cells in column Season4 End Date using expression value.toDate()\n',
 '#@param col-name:Season4_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table26\n',
 '#@out table27\n',
 '#@end core/text-transform25\n',
 '#@begin core/column-removal0#@desc Remove column Column\n',
 '#@param col-name:Column\n',
 '#@in table27\n',
 '#@out table28\n',
 '#@end core/column-removal0\n',
 '#@begin core/text-transform26#@desc Text transform on cells in column updateTime using expression value.trim()\n',
 '#@param col-name:updateTime\n',
 '#@param expression:value.trim()\n',
 '#@in table28\n',
 '#@out table29\n',
 '#@end core/text-transform26\n',
 "#@begin core/text-transform27#@desc Text transform on cells in column updateTime using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:updateTime\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table29\n',
 '#@out table30\n',
 '#@end core/text-transform27\n',
 '#@begin core/text-transform28#@desc Text transform on cells in column updateTime using expression value.toDate()\n',
 '#@param col-name:updateTime\n',
 '#@param expression:value.toDate()\n',
 '#@in table30\n',
 '#@out table31\n',
 '#@end core/text-transform28\n',
 '#@begin core/text-transform29#@desc Text transform on cells in column Season1 Start Date using expression value.trim()\n',
 '#@param col-name:Season1_Start_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table31\n',
 '#@out table32\n',
 '#@end core/text-transform29\n',
 "#@begin core/text-transform30#@desc Text transform on cells in column Season1 Start Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season1_Start_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table32\n',
 '#@out table33\n',
 '#@end core/text-transform30\n',
 '#@begin core/text-transform31#@desc Text transform on cells in column Season1 Start Date using expression value.toDate()\n',
 '#@param col-name:Season1_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table33\n',
 '#@out table34\n',
 '#@end core/text-transform31\n',
 '#@begin core/text-transform32#@desc Text transform on cells in column Season1 End Date using expression value.trim()\n',
 '#@param col-name:Season1_End_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table34\n',
 '#@out table35\n',
 '#@end core/text-transform32\n',
 "#@begin core/text-transform33#@desc Text transform on cells in column Season1 End Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season1_End_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table35\n',
 '#@out table36\n',
 '#@end core/text-transform33\n',
 '#@begin core/text-transform34#@desc Text transform on cells in column Season1 End Date using expression value.toDate()\n',
 '#@param col-name:Season1_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table36\n',
 '#@out table37\n',
 '#@end core/text-transform34\n',
 '#@begin core/text-transform35#@desc Text transform on cells in column Season2 Start Date using expression value.trim()\n',
 '#@param col-name:Season2_Start_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table37\n',
 '#@out table38\n',
 '#@end core/text-transform35\n',
 "#@begin core/text-transform36#@desc Text transform on cells in column Season2 Start Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season2_Start_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table38\n',
 '#@out table39\n',
 '#@end core/text-transform36\n',
 '#@begin core/text-transform37#@desc Text transform on cells in column Season2 Start Date using expression value.toDate()\n',
 '#@param col-name:Season2_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table39\n',
 '#@out table40\n',
 '#@end core/text-transform37\n',
 '#@begin core/text-transform38#@desc Text transform on cells in column Season2 End Date using expression value.trim()\n',
 '#@param col-name:Season2_End_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table40\n',
 '#@out table41\n',
 '#@end core/text-transform38\n',
 "#@begin core/text-transform39#@desc Text transform on cells in column Season2 End Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season2_End_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table41\n',
 '#@out table42\n',
 '#@end core/text-transform39\n',
 '#@begin core/text-transform40#@desc Text transform on cells in column Season2 End Date using expression value.toDate()\n',
 '#@param col-name:Season2_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table42\n',
 '#@out table43\n',
 '#@end core/text-transform40\n',
 "#@begin core/text-transform41#@desc Text transform on cells in column Season3 Start Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season3_Start_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table43\n',
 '#@out table44\n',
 '#@end core/text-transform41\n',
 '#@begin core/text-transform42#@desc Text transform on cells in column Season3 Start Date using expression value.trim()\n',
 '#@param col-name:Season3_Start_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table44\n',
 '#@out table45\n',
 '#@end core/text-transform42\n',
 '#@begin core/text-transform43#@desc Text transform on cells in column Season3 Start Date using expression value.toDate()\n',
 '#@param col-name:Season3_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table45\n',
 '#@out table46\n',
 '#@end core/text-transform43\n',
 '#@begin core/text-transform44#@desc Text transform on cells in column Season3 End Date using expression value.trim()\n',
 '#@param col-name:Season3_End_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table46\n',
 '#@out table47\n',
 '#@end core/text-transform44\n',
 '#@begin core/text-transform45#@desc Text transform on cells in column Season4 Start Date using expression value.trim()\n',
 '#@param col-name:Season4_Start_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table47\n',
 '#@out table48\n',
 '#@end core/text-transform45\n',
 '#@begin core/text-transform46#@desc Text transform on cells in column Season4 End Date using expression value.trim()\n',
 '#@param col-name:Season4_End_Date\n',
 '#@param expression:value.trim()\n',
 '#@in table48\n',
 '#@out table49\n',
 '#@end core/text-transform46\n',
 "#@begin core/text-transform47#@desc Text transform on cells in column Season3 End Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season3_End_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table49\n',
 '#@out table50\n',
 '#@end core/text-transform47\n',
 "#@begin core/text-transform48#@desc Text transform on cells in column Season4 Start Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season4_Start_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table50\n',
 '#@out table51\n',
 '#@end core/text-transform48\n',
 "#@begin core/text-transform49#@desc Text transform on cells in column Season4 End Date using expression value.replace(/\\\\s+/,' ')\n",
 '#@param col-name:Season4_End_Date\n',
 "#@param expression:value.replace(/\\\\s+/,'_')\n",
 '#@in table51\n',
 '#@out table52\n',
 '#@end core/text-transform49\n',
 '#@begin core/text-transform50#@desc Text transform on cells in column Season3 End Date using expression value.toDate()\n',
 '#@param col-name:Season3_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table52\n',
 '#@out table53\n',
 '#@end core/text-transform50\n',
 '#@begin core/text-transform51#@desc Text transform on cells in column Season4 Start Date using expression value.toDate()\n',
 '#@param col-name:Season4_Start_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table53\n',
 '#@out table54\n',
 '#@end core/text-transform51\n',
 '#@begin core/text-transform52#@desc Text transform on cells in column Season4 End Date using expression value.toDate()\n',
 '#@param col-name:Season4_End_Date\n',
 '#@param expression:value.toDate()\n',
 '#@in table54\n',
 '#@out table55\n',
 '#@end core/text-transform52\n',
 '#@end Linear_OR\n']